In [3]:
import seaborn as sns
import pandas as pd
import cufflinks as cf
from plotly.offline import iplot

In [4]:
tips = sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
import plotly

print(plotly.__version__)

from plotly.graph_objs import Scatter

print(Scatter())

5.24.1
Scatter()

In [6]:
import pandas as pd
import cufflinks as cf

print(pd.__version__)
print(cf.__version__)

2.2.3
0.17.3

In [7]:
import plotly.express as px

fig = px.line(tips, y="total_bill")
fig.show()

In [8]:
fig = px.histogram(tips, x="total_bill")
fig.show()

In [15]:
import plotly.express as px

df = tips.groupby("day", as_index=False)["tip"].mean()

fig = px.bar(df, x="day", y="tip")
fig.show()

C:\Users\amitc\AppData\Local\Temp\ipykernel_960\3117564031.py:3: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [16]:
import pandas as pd
import plotly
import cufflinks as cf

print(pd.__version__)
print(plotly.__version__)
print(cf.__version__)

2.2.3
5.24.1
0.17.3

In [17]:
import seaborn as sns
import cufflinks as cf

cf.go_offline()

tips = sns.load_dataset("tips")

tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
import plotly.express as px

df = tips.groupby("day", as_index=False)["tip"].mean()

fig = px.bar(df, x="day", y="tip")

fig.show()

C:\Users\amitc\AppData\Local\Temp\ipykernel_960\2562025474.py:3: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [21]:
tips.iplot(kind='Scatter',x='total_bill',y='tip')

PlotlyEmptyDataError: Empty data list found. Make sure that you populated the list of data objects you're sending and try again.
Questions? Visit support.plot.ly