## Missing data

In [29]:
import numpy as np
import pandas as pd

In [9]:
data = {
    'A': [1,2,np.nan,4,5],
    'B': [1,2,3,4,5],
    'C': [1,2,3,np.nan,np.nan],
    'D': [1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [ ]:
#check null value
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [5]:
#count how many null value are there
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [ ]:
#check column wise null available or not // searching
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [10]:
#remove row of null values
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [11]:
#print condition wise null value
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [12]:
#filling the missing data
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [13]:
#fill the different value for each column
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [15]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# merging joining and concatination

In [32]:
#merging 2 data frames
emp = pd.DataFrame({
    'emp_id': [1,2,3,4,5],
    'name': ['john','Anna','peter','linda','bob'],
    'department': ['HR','IT','Finance','IT','HR']
})

#Dataframe 2: salary information
salary = pd.DataFrame({
    'emp_id': [1,2,3,6,7],
    'salary': [60000,80000,65000,70000,90000],
    'bonus': [5000,10000,7000,8000,12000]
})

In [20]:
emp

   emp_id   name department
0       1   john         HR
1       2   Anna         IT
2       3  peter    Finance
3       4  linda         IT
4       5    bob         HR

In [21]:
salary

   emp_id  salary  bonus
0       1   60000   5000
1       2   80000  10000
2       3   65000   7000
3       6   70000   8000
4       7   90000  12000

In [23]:
#merge id with salary
pd.merge(emp,salary,on='emp_id',how='inner')

   emp_id   name department  salary  bonus
0       1   john         HR   60000   5000
1       2   Anna         IT   80000  10000
2       3  peter    Finance   65000   7000

In [24]:
pd.merge(emp,salary,on='emp_id',how='outer')

   emp_id   name department   salary    bonus
0       1   john         HR  60000.0   5000.0
1       2   Anna         IT  80000.0  10000.0
2       3  peter    Finance  65000.0   7000.0
3       4  linda         IT      NaN      NaN
4       5    bob         HR      NaN      NaN
5       6    NaN        NaN  70000.0   8000.0
6       7    NaN        NaN  90000.0  12000.0

In [25]:
pd.merge(emp,salary,on='emp_id',how='left')

   emp_id   name department   salary    bonus
0       1   john         HR  60000.0   5000.0
1       2   Anna         IT  80000.0  10000.0
2       3  peter    Finance  65000.0   7000.0
3       4  linda         IT      NaN      NaN
4       5    bob         HR      NaN      NaN

In [26]:
pd.merge(emp,salary,on='emp_id',how='right')

   emp_id   name department  salary  bonus
0       1   john         HR   60000   5000
1       2   Anna         IT   80000  10000
2       3  peter    Finance   65000   7000
3       6    NaN        NaN   70000   8000
4       7    NaN        NaN   90000  12000

In [34]:
#concatination of data frame
df1 = pd.DataFrame({
    'A': ['A0','A1','A2'],
    'B': ['B0','B2','B3'],
    'C': ['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A': ['A3','A4','A5'],
    'B': ['B3','B4','B5'],
    'C': ['C3','C3','C5']
})

In [35]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B2  C1
2  A2  B3  C2

In [36]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C3
2  A5  B5  C5

In [38]:
pd.concat((df1,df2))

    A   B   C
0  A0  B0  C0
1  A1  B2  C1
2  A2  B3  C2
0  A3  B3  C3
1  A4  B4  C3
2  A5  B5  C5

In [39]:
pd.concat((df1,df2),axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B2  C1  A4  B4  C3
2  A2  B3  C2  A5  B5  C5

In [40]:
#joining 2 data frames
df1 = pd.DataFrame({
    'name': ['alice','bob','charlie'],
}, index=[1,2,3])

df2= pd.DataFrame({
    'score': [85,90,75]
}, index=[2,3,4])

In [41]:
df1

      name
1    alice
2      bob
3  charlie

In [42]:
df2

   score
2     85
3     90
4     75

In [43]:
df1.join(df2,how='outer')

      name  score
1    alice    NaN
2      bob   85.0
3  charlie   90.0
4      NaN   75.0