In [1]:
import numpy as np
import pandas as pd

##pandas refers to  panel data

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

#pd.Series(my_list)
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [3]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

## Creating data frame

In [4]:
data = {
    'name' : ['john','anna','peter','linda'],
    'age': [28,34,29,42],
    'city': ['new york','paris','berlin','london'],
    'salary': [65000,70000,62000,85000]

}
pd.DataFrame(data)

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [7]:
data_list = [
    ['john',28,	'new york',	65000],
	['anna',34,	'paris',	70000],
	['peter',29,'berlin',	62000],
	['linda',42,'london',	85000]

]
df2 = pd.DataFrame(data_list)
columns = ['name','age','city','salary']
df2 = pd.DataFrame(data_list,columns=columns)
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [ ]:
## select column
#df2['name']

df2[['name','city']]

    name      city
0   john  new york
1   anna     paris
2  peter    berlin
3  linda    london

In [ ]:
#add new column
df2["designation"] = ['doc','eng','doc','eng']
df2

    name  age      city  salary designation
0   john   28  new york   65000         doc
1   anna   34     paris   70000         eng
2  peter   29    berlin   62000         doc
3  linda   42    london   85000         eng

In [16]:
#remove a column
df2.drop(['city','salary'],axis=1)

    name  age
0   john   28
1   anna   34
2  peter   29
3  linda   42

In [14]:
# remove column completely
df2.drop('designation',axis=1,inplace = True)

In [18]:
#remove row
df2.drop(1,axis= 0)

    name  age      city  salary
0   john   28  new york   65000
2  peter   29    berlin   62000
3  linda   42    london   85000

## Selecting a row

In [ ]:
#for single selection
df2.loc[0]

name          john
age             28
city      new york
salary       65000
Name: 0, dtype: object

In [21]:
#for multiple selection
df2.loc[[0,1]]

   name  age      city  salary
0  john   28  new york   65000
1  anna   34     paris   70000

In [22]:
# for select indexwise
df2.iloc[3]

name       linda
age           42
city      london
salary     85000
Name: 3, dtype: object

## selecting subset of rows and columns

In [23]:
df2.loc[[0,1]][['city','salary']]

       city  salary
0  new york   65000
1     paris   70000

In [24]:
df2.loc[[2,3]][['name','age']]

    name  age
2  peter   29
3  linda   42

## conditional selection

In [25]:
# i only want to see those people whose age is above 30
df2[df2['age'] > 30]

    name  age    city  salary
1   anna   34   paris   70000
3  linda   42  london   85000

In [27]:
#i only want people whose age is above 30 and their city must be paris
df2[(df2['age'] > 30) & (df2['city'] == 'paris')]

   name  age   city  salary
1  anna   34  paris   70000